apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsrecords.cloudflare.dns.kangdroid.dev
spec:
  group: cloudflare.dns.kangdroid.dev
  names:
    kind: dnsrecord
    listKind: dnsrecordList
    plural: dnsrecords
    singular: dnsrecord
  scope: Namespaced
  versions:
  - name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            items:
              properties:
                lastSynced:
                  format: date-time
                  type: string
                syncStatus:
                  enum:
                  - RecordCreated
                  - RecordAlreadySynced
                  type: string
                response:
                  type: string
              type: object
            type: array
          spec:
            description: Specification of the kubernetes object.
            properties:
              accountId:
                type: string
              zone:
                type: string
              apiKey:
                type: string
              content:
                type: string
              name:
                type: string
              proxied:
                type: boolean
              type:
                type: string
              comment:
                type: string
              ttl:
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}