apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsrecords.cloudflare.dns.kangdroid.dev
spec:
  group: cloudflare.dns.kangdroid.dev
  names:
    kind: dnsrecord
    listKind: dnsrecordList
    plural: dnsrecords
    singular: dnsrecord
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Type of the DNS Record
      jsonPath: .spec.dnsRecordConfig.type
      name: Type
      priority: 0
      type: string
    - description: DNS Management Name(IP Address when type = a, CNAME when type = CNAME) of the DNS Record
      jsonPath: .spec.dnsRecordConfig.name
      name: DNS Record Name
      priority: 0
      type: string
    - description: DNS Content(Target)
      jsonPath: .spec.dnsRecordConfig.content
      name: Content
      priority: 0
      type: string
    name: v1alpha
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              lastConfiguration:
                properties:
                  content:
                    type: string
                  name:
                    type: string
                  proxied:
                    type: boolean
                  type:
                    type: string
                  comment:
                    type: string
                  ttl:
                    format: int32
                    type: integer
                type: object
              syncLog:
                items:
                  properties:
                    lastSynced:
                      format: date-time
                      type: string
                    syncStatus:
                      enum:
                      - RecordCreated
                      - RecordUpdated
                      - RecordAlreadySynced
                      - RecordNotExists
                      - SecretInvalid
                      type: string
                    response:
                      type: string
                  type: object
                type: array
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              cloudflareSecretRef:
                properties:
                  name:
                    type: string
                type: object
              dnsRecordConfig:
                properties:
                  content:
                    type: string
                  name:
                    type: string
                  proxied:
                    type: boolean
                  type:
                    type: string
                  comment:
                    type: string
                  ttl:
                    format: int32
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}