apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: operator-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operator-certificate
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: operator-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io